#!/bin/sh
cat welcome.txt > tmp.txt
cat license.txt >> tmp.txt
cat ../gopherus.txt >> tmp.txt
echo '/* THIS FILE IS AUTOGENERATED BY GENDICT.SH */' > idict.h
./grams tmp.txt 4 | grep -A100 'char gramdict\[\]' >> idict.h
rm tmp.txt
